spring.application.name=cbs
# ===========================================
# MICROSERVICIO DE CUENTAS - ARCBANK
# ===========================================

# ===========================================
# CONFIGURACIÓN DE BASE DE DATOS POSTGRESQL
# ===========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_cuentas
spring.datasource.username=postgres
spring.datasource.password=TU_CLAVE_AQUI
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================================
# CONFIGURACIÓN JPA / HIBERNATE
# ===========================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================================
# PUERTO DEL MICROSERVICIO
# ===========================================
server.port=8083

# ===========================================
# LOGGING SQL (ÚTIL PARA DEPURAR)
# ===========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
